### ISSUE TITLE
Suggestion: update the README's example section as a table

### ISSUE THREAD

**Issue by ykdojo** [logankilpatrick/ChatGPT-Plugins-Collection#6]
I'm thinking like this:

## Examples 👀 😯:

| Plugin Name  | Description | Language | Framework |
|--------------|-------------|----------|-----------|
| [NotesGPT](https://github.com/logankilpatrick/ChatGPT-Plugins-Collection/tree/main/python/NotesGPT) | (Description of NotesGPT plugin) | Python | (Framework) |
| [TodoGPT](https://github.com/logankilpatrick/ChatGPT-Plugins-Collection/tree/main/python/TodoGPT) | (Description of TodoGPT plugin) | Python | (Framework) |
| [AnimalGPT](https://github.com/logankilpatrick/ChatGPT-Plugins-Collection/tree/main/julia/AnimalGPT) | (Description of AnimalGPT plugin) | Julia | (Framework) |
| [SquareGPT](https://github.com/logankilpatrick/ChatGPT-Plugins-Collection/tree/main/julia/SquareGPT) | (Description of SquareGPT plugin) | Julia | (Framework) |
| [secretMessage](https://github.com/logankilpatrick/ChatGPT-Plugins-Collection/tree/main/python/secretMessage) | (Description of secretMessage plugin) | Python | (Framework) |

**Comment by logankilpatrick** [comment]
If you make a PR, I can merge : )
